### ISSUE TITLE
ns\Hydra\Modules\Automation.lua:105: attempt to compare nil with number

### ISSUE THREAD

**Issue by Thrumbar** [Phanx/Hydra#11]
Cannot sell greys.  Disabled all addons but hydra and get this error when going to merchant to repair and sell greys. Getting this even after UI reset with nothing but Hydra installed.  Also this error does not appear on all my characters just some.

Message: Interface\AddOns\Hydra\Modules\Automation.lua:105: attempt to compare nil with number
Time: 05/01/15 12:27:59
Count: 2
Stack: Interface\AddOns\Hydra\Modules\Automation.lua:105: in function `?'
Interface\AddOns\Hydra\Core.lua:221: in function <Interface\AddOns\Hydra\Core.lua:220>

Locals: self = <unnamed> {
 0 = <userdata>
 defaults = <table> {
 }
 CONFIRM_SUMMON = <function> defined @Interface\AddOns\Hydra\Modules\Automation.lua:163
 Enable = <function> defined @Interface\AddOns\Hydra\Core.lua:182
 Print = <function> defined @Interface\AddOns\Hydra\Modules\Automation.lua:58
 ARENA_TEAM_INVITE_REQUEST = <function> defined @Interface\AddOns\Hydra\Modules\Automation.lua:79
 PETITION_SHOW = <function> defined @Interface\AddOns\Hydra\Modules\Automation.lua:66
 PLAYER_REGEN_ENABLED = <function> defined @Interface\AddOns\Hydra\Modules\Automation.lua:158
 db = <table> {
 }
 MERCHANT_SHOW = <function> defined @Interface\AddOns\Hydra\Modules\Automation.lua:93
 enabled = true
 SetupOptions = <function> defined @Interface\AddOns\Hydra\Modules\Automation.lua:182
 Debug = <function> defined @Interface\AddOns\Hydra\Core.lua:47
 displayName = "Automation"
 RESURRECT_REQUEST = <function> defined @Interface\AddOns\Hydra\Modules\Automation.lua:147
 Refresh = <function> defined @Interface\AddOns\Hydra\Core.lua:201
 DUEL_REQUESTED = <function> defined @Interface\AddOns\Hydra\Modules\Automation.lua:85
 SendChatMessage = <function> defined @Interface\AddOns\Hydra\Core.lua:83
 ShouldEnable = <function> defined @Interface\AddOns\Hydra\Core.lua:209
 OnEnable = <function> defined @Interface\AddOns\Hydra\Modules\Automation.lua:37
 name = "Automation"
 debug = true
 IsEnabled = <function> defined @Interface\AddOns\Hydra\Core.lua:179
 SendAddonMessage = <function> defined @Interface\AddOns\Hydra\Core.lua:68
 Alert = <function> defined @Interface\AddOns\Hydra\Core.lua:64
 Disable = <function> defined @Interface\AddOns\Hydra\Core.lua:191
}
num = 0
value = 0
(for index) = 1
(for limit) = 4
(for step) = 1
bag = 1
(for index) = 14
(for limit) = 22
(for step) = 1
slot = 14
link = "[Peanut]"
_ = nil
_ = nil
q = nil
_ = nil
_ = nil
_ = nil
_ = nil
_ = nil
_ = nil
_ = nil
v = nil
(*temporary) = "Interface\ICONS\INV_Misc_Note_01.blp"
(*temporary) = 0
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare nil with number"
L = <table> {
 MountTogether = "Mount with group"
 AcceptCombatRes_Info = "Accept resurrections in combat from all group members."
 Mount = "Mount"
 Follow = "Follow"
 DeclineDuels_Info = "Decline duel requests from all players."
 CantRes = "%s cannot be resurrected!"
 SlashPromoteMe = "/promoteme"
 FollowingYouStop = "%s is no longer following you."
 AcceptSummons = "Accept summons"
 WhisperTimeoutError = "Whisper timeout reached."
 AddGroup = "Add Group"
 WhisperFromGM = "%s has received a whisper from a GM!"
 Assist_Info = "Synchronizes an assist target across trusted group members."
 DeclineArenas = "Decline arena teams"
 AssistRespond = "Assist"
 SlashCorpse = "/corpse"
 Dismount_Info = "Dismount when another trusted group member dismounts."
 QuestAccepted = "%1$s accepted %2$s."
 ShareQuests_Info = "Automatically share quests you pick up from NPCs."
 RemovedTrusted = "%s has been removed from your trusted list."
 RefollowAfterCombat_Info = "Automatically try to follow your last followed target when leaving combat."
 GroupLeader = "Group leader"
 MountTogether_Info = "Mount when another trusted group member mounts."
 Follow_Info = "Responds to follow requests from trusted group members."
 AcceptedSummon = "Accepting a summon from %1$s to %2$s."
 RemoveEmpty = "Your trusted list is empty."
 AcceptCorpse_Info = "Set a key binding to direct dead group members to accept resurrection to their corpse."
 AcceptedSummonCombat = "Accepting a summon when combat ends..."
 DeclineGuilds = "Decline guilds"
 NoRepairMoney = "Insufficient funds to repair!"
 AssistFailedTrust = "%s cannot assist you because you are

**Comment by Thrumbar** [comment]
Possible issue found here

link = "[Peanut]"
_ = nil
_ = nil
q = nil
_ = nil
_ = nil
_ = nil
_ = nil
_ = nil
_ = nil
_ = nil
v = nil

had to put various pets in cages for Childrens Week and when I removed them the error no longer there.  The issue appears to be with the caged pets in the inventories of the affected characters.

**Comment by Phanx** [comment]
This was actually fixed a while ago, but apparently I forgot to tag a release...
