### ISSUE TITLE
No Options

### ISSUE THREAD

**Issue by quirkycat** [Phanx/Hydra#13]
Since this morning (new Hydra update) I am unable to access options.
/hydra is not recognised.
Interface>AddOns?Hydra only has About visible

**Comment by Phanx** [comment]
Please read this and follow the instructions to enable error reporting:
http://phanx.net/addons/help#errors
After you've done that, post the error message you're getting. If there are more than one, just post the first one.

**Comment by quirkycat** [comment]
Message: ...hanxConfig-OptionsPanel\PhanxConfig-OptionsPanel.lua:41: Interface\AddOns\Hydra\Core.lua:365: attempt to index upvalue 'L' (a nil value)
Time: 08/11/15 09:54:00
Count: 1
Stack: [C]: ?
[C]: in function `error'
...hanxConfig-OptionsPanel\PhanxConfig-OptionsPanel.lua:41: in function <...hanxConfig-OptionsPanel\PhanxConfig-OptionsPanel.lua:37>
[C]: in function `Show'
Interface\FrameXML\InterfaceOptionsFrame.lua:28: in function `InterfaceOptionsList_DisplayPanel'
Interface\FrameXML\InterfaceOptionsFrame.lua:46: in function `InterfaceOptionsListButton_OnClick'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

Locals:
