### ISSUE TITLE
Issues With last update 6.2.0.30 10 total listed

### ISSUE THREAD

**Issue by Thrumbar** [Phanx/Hydra#14]
This is all that showed up in bug sack for theses errors 

1x Hydra\Localization.lua:27: '=' expected near '/'
Locals:

1x Hydra\Modules\Automation.lua:180: attempt to index local 'L' (a nil value)
Hydra\Modules\Automation.lua:180: in main chunk
Locals:

1x Hydra\Modules\Chat-Chat.lua:41: attempt to index local 'L' (a nil value)
Hydra\Modules\Chat-Chat.lua:41: in main chunk
Locals:

1x Hydra\Modules\Follow-Follow.lua:183: attempt to index local 'L' (a nil value)
Hydra\Modules\Follow-Follow.lua:183: in main chunk
Locals:

1x Hydra\Modules\Group-Group.lua:132: attempt to index local 'L' (a nil value)
Hydra\Modules\Group-Group.lua:132: in main chunk
Locals:

1x Hydra\Modules\Loot-Loot.lua:51: attempt to index local 'L' (a nil value)
Hydra\Modules\Loot-Loot.lua:51: in main chunk
Locals:

1x Hydra\Modules\Mount-Mount.lua:215: attempt to index local 'L' (a nil value)
Hydra\Modules\Mount-Mount.lua:215: in main chunk
Locals:

1x Hydra\Modules\Quest.lua:493: attempt to index local 'L' (a nil value)
Hydra\Modules\Quest.lua:493: in main chunk
Locals:

1x Hydra\Modules\Taxi.lua:96: attempt to index local 'L' (a nil value)
Hydra\Modules\Taxi.lua:96: in main chunk
Locals:

1x Hydra\Options-Options.lua:52: attempt to index local 'L' (a nil value)
Hydra\Options-Options.lua:52: in main chunk
Locals:

**Comment by Phanx** [comment]
Sigh, good old CurseForge packager...
