### ISSUE TITLE
Hydra\Modules\Loot-Loot.lua:35: attempt to compare nil with number

### ISSUE THREAD

**Issue by Thrumbar** [Phanx/Hydra#15]
1x Hydra\Modules\Loot-Loot.lua:35: attempt to compare nil with number
Hydra\Modules\Loot-Loot.lua:35: in function `OnStateChange'
Hydra\Core.lua:343: in function `?'
Hydra\Core.lua:248: in function <Hydra\Core.lua:248>

Locals:
self = <unnamed> {
 0 = <userdata>
 UNIT_NAME_UPDATE = <function> defined @Hydra\Core.lua:307
 CHAT_MSG_ADDON = <function> defined @Hydra\Core.lua:293
 PARTY_LEADER_CHANGED = <function> defined @Hydra\Core.lua:307
 PLAYER_LOGIN = <function> defined @Hydra\Core.lua:251
 PARTY_LOOT_METHOD_CHANGED = <function> defined @Hydra\Core.lua:307
 GROUP_ROSTER_UPDATE = <function> defined @Hydra\Core.lua:307
 CheckParty = <function> defined @Hydra\Core.lua:307
}
unit = nil
newstate = 3
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 Taxi = <unnamed> {
 }
 Mount = <unnamed> {
 }
 Loot = <unnamed> {
 }
 Automation = <unnamed> {
 }
 Group = <unnamed> {
 }
 Follow = <unnamed> {
 }
 Quest = <unnamed> {
 }
 Chat = <unnamed> {
 }
}
(for control) = "Loot"
name = "Loot"
module = <unnamed> {
 0 = <userdata>
 defaults = <table> {
 }
 Enable = <function> defined @Hydra\Core.lua:176
 Print = <function> defined @Hydra\Core.lua:50
 db = <table> {
 }
 OnStateChange = <function> defined @Hydra\Modules\Loot.lua:32
 enabled = true
 Debug = <function> defined @Hydra\Core.lua:41
 Refresh = <function> defined @Hydra\Core.lua:195
 SendChatMessage = <function> defined @Hydra\Core.lua:77
 OnEnable = <function> defined @Hydra\Modules\Loot.lua:27
 name = "Loot"
 ShouldEnable = <function> defined @Hydra\Modules\Loot.lua:23
 IsEnabled = <function> defined @Hydra\Core.lua:173
 SendAddonMessage = <function> defined @Hydra\Core.lua:62
 Alert = <function> defined @Hydra\Core.lua:58
 Disable = <function> defined @Hydra\Core.lua:185
}
enable = true
groupUnits = <table> {
 raid14 = true
 raid18 = true
 party3 = true
 raid4 = true
 raid9 = true
 raid3 = true
 raid22 = true
 raid13 = true
 raid23 = true
 raid6 = true
 raid7 = true
 raid35 = true
 raid12 = true
 raid16 = true
 raid19 = true
 raid39 = true
 raid26 = true
 raid27 = true
 raid10 = true
 raid37 = true
 raid17 = true
 raid38 = true
 raid40 = true
 raid36 = true
 raid34 = true
 party4 = true
 raid2 = true
 raid31 = true
 raid33 = true
 raid20 = true
 raid24 = true
 party2 = true
 raid5 = true
 raid21 = true
 raid28 = true
 raid25 = true
 raid8 = true
 raid32 = true
 raid1 = true
 raid29 = true
 raid11 = true
 party1 = true
 raid30 = true
 raid15 = true
}
SOLO = 0
Hydra = <table> {
 STATE_PARTY = 1
 STATE_TRUSTED = 2
 NewModule = <function> defined @Hydra\Core.lua:209
 Print = <function> defined @Hydra\Core.lua:50
 modules = <table> {
 }
 GetModule = <function> defined @Hydra\Core.lua:226
 state = 3
 db = <table> {
 }
 PLAYER_FULLNAME = "Falent-Hellscream"
 Debug = <function> defined @Hydra\Core.lua:41
 SetupOptions = <function> defined @Hydra\Core.lua:364
 TriggerEvent = <function> defined @Hydra\Core.lua:356
 RemoveTrusted = <function> defined @Hydra\Core.lua:154
 STATE_SOLO = 0
 ValidateName = <function> defined @Hydra\Core.lua:109
 IsTrusted = <function> defined @Hydra\Core.lua:130
 GetPlayerInfo = <function> defined @Hydra\Core.lua:33
 AddTrusted = <function> defined @Hydra\Core.lua:143
 SendChatMessage = <function> defined @Hydra\Core.lua:77
 trusted = <table> {
 }
 PLAYER_NAME = "Falent"
 name = "Hydra"
 STATE_LEADER = 3
 SendAddonMessage = <function> defined @Hydra\Core.lua:62
 GetStateFlags = <function> defined @Hydra\Core.lua:23
 Alert = <function> defined @Hydra\Core.lua:58
 PLAYER_REALM = "Hellscream"
}
INSECURE = 1
LEADER = 3
SECURE = 2

**Comment by Phanx** [comment]
Probably a consequence of the other error you reported. Let me know if you're still getting it with the new version.

**Comment by Thrumbar** [comment]
still getting this error and the group does not change to ffa nor is there an ability to make the change in the settings

**Comment by hydra** [comment]
Can you please avoid pasting in `@Hydra` without escaping it otherwise I get github email notifications.

bad:

@Hydra

good:

`@Hydra`

Thanks!
