### ISSUE TITLE
Hydra\Modules\Quest.lua:159: attempt to concatenate local 'title' (a boolean value)

### ISSUE THREAD

**Issue by Thrumbar** [Phanx/Hydra#22]
Got this upon turning in quest "Natures Call"..  This error only occoured on my Gaurdian Druid and not on my Holy Paladin.

1x Hydra\Modules\Quest.lua:159: attempt to concatenate local 'title' (a boolean value)
Hydra\Modules\Quest.lua:159: in function `?'
Hydra\Core.lua:211: in function <Hydra\Core.lua:210>

Locals:
self = <unnamed> {
 0 = <userdata>
 defaults = <table> {
 }
 QUEST_FINISHED = <function> defined @Hydra\Modules\Quest.lua:327
 QUEST_GREETING = <function> defined @Hydra\Modules\Quest.lua:185
 Enable = <function> defined @Hydra\Core.lua:172
 Print = <function> defined @Hydra\Core.lua:46
 QUEST_LOG_UPDATE = <function> defined @Hydra\Modules\Quest.lua:354
 QUEST_AUTOCOMPLETE = <function> defined @Hydra\Modules\Quest.lua:334
 QUEST_COMPLETE = <function> defined @Hydra\Modules\Quest.lua:290
 QUEST_ITEM_UPDATE = <function> defined @Hydra\Modules\Quest.lua:284
 SetupOptions = <function> defined @Hydra\Options.lua:14
 db = <table> {
 }
 GOSSIP_SHOW = <function> defined @Hydra\Modules\Quest.lua:142
 displayName = "Quest"
 OptionsPanel = <unnamed> {
 }
 enabled = true
 QUEST_PROGRESS = <function> defined @Hydra\Modules\Quest.lua:274
 Debug = <function> defined @Hydra\Core.lua:37
 QUEST_ACCEPTED = <function> defined @Hydra\Modules\Quest.lua:262
 QUEST_DETAIL = <function> defined @Hydra\Modules\Quest.lua:223
 Refresh = <function> defined @Hydra\Core.lua:191
 ShouldEnable = <function> defined @Hydra\Modules\Quest.lua:50
 SendChatMessage = <function> defined @Hydra\Core.lua:73
 OnAddonMessage = <function> defined @Hydra\Modules\Quest.lua:87
 OnEnable = <function> defined @Hydra\Modules\Quest.lua:54
 name = "Quest"
 QUEST_ACCEPT_CONFIRM = <function> defined @Hydra\Modules\Quest.lua:249
 IsEnabled = <function> defined @Hydra\Core.lua:169
 SendAddonMessage = <function> defined @Hydra\Core.lua:58
 Alert = <function> defined @Hydra\Core.lua:54
 Disable = <function> defined @Hydra\Core.lua:181
}
(for index) = 2
(for limit) = 3
(for step) = 1
i = 2
title = false
level = "Archdruid of the Claw"
isLowLevel = -1
isDaily = false
isRepeatable = 1
isLegendary = false
(*temporary) = <function> defined @Hydra\Core.lua:37
(*temporary) = <unnamed> {
 0 = <userdata>
 defaults = <table> {
 }
 QUEST_FINISHED = <function> defined @Hydra\Modules\Quest.lua:327
 QUEST_GREETING = <function> defined @Hydra\Modules\Quest.lua:185
 Enable = <function> defined @Hydra\Core.lua:172
 Print = <function> defined @Hydra\Core.lua:46
 QUEST_LOG_UPDATE = <function> defined @Hydra\Modules\Quest.lua:354
 QUEST_AUTOCOMPLETE = <function> defined @Hydra\Modules\Quest.lua:334
 QUEST_COMPLETE = <function> defined @Hydra\Modules\Quest.lua:290
 QUEST_ITEM_UPDATE = <function> defined @Hydra\Modules\Quest.lua:284
 SetupOptions = <function> defined @Hydra\Options.lua:14
 db = <table> {
 }
 GOSSIP_SHOW = <function> defined @Hydra\Modules\Quest.lua:142
 displayName = "Quest"
 OptionsPanel = <unnamed> {
 }
 enabled = true
 QUEST_PROGRESS = <function> defined @Hydra\Modules\Quest.lua:274
 Debug = <function> defined @Hydra\Core.lua:37
 QUEST_ACCEPTED = <function> defined @Hydra\Modules\Quest.lua:262
 QUEST_DETAIL = <function> defined @Hydra\Modules\Quest.lua:223
 Refresh = <function> defined @Hydra\Core.lua:191
 ShouldEnable = <function> defined @Hydra\Modules\Quest.lua:50
 SendChatMessage = <function> defined @Hydra\Core.lua:73
 OnAddonMessage = <function> defined @Hydra\Modules\Quest.lua:87
 OnEnable = <function> defined @Hydra\Modules\Quest.lua:54
 name = "Quest"
 QUEST_ACCEPT_CONFIRM = <function> defined @Hydra\Modules\Quest.lua:249
 IsEnabled = <function> defined @Hydra\Core.lua:169
 SendAddonMessage = <function> de

**Comment by hydra** [comment]
please remember to quote code.

```
like this
```

otherwise I get notified due to the inclusion of `@hydra' in the code snippet above.

**Comment by Phanx** [comment]
@hydra That's probably a lost cause. I've been trying to get people to format code correctly in bug reports for years, and it just doesn't happen. On the bright side, it's not like this is a very active project, so you shouldn't get pestered too often.

**Comment by hydra** [comment]
:smile: thanks
