### ISSUE TITLE
Request: Flight Master's Whistle across characters

### ISSUE THREAD

**Issue by Zamaza** [Phanx/Hydra#23]
With Legion's new Flight Master's Whistle item, it would be nice if when I used this on one character, the other(s) used it as well. Similar to how the mounting works now.

I have a macro to do this right now, but it would probably be a nice feature.

**Comment by Phanx** [comment]
On October 18, 2016 1:19:16 AM PDT, Zamaza notifications@github.com wrote:

> With Legion's new Flight Master's Whistle item, it would be nice if
> when I used this on one character, the other(s) used it as well.
> Similar to how the mounting works now.
> 
> I have a macro to do this right now, but it would probably be a nice
> feature.

Not possible. Using an item requires a hardware action (mouse click or key press) so an addon can't use an item automatically. Summoning a mount does not require a hardware action, so an addon can do that as much as it likes.

Using a item on multiple characters, like casting a spell, requires both game clients to receive a hardware event and have that specific event bound to a macro or action that invokes the item.
