### ISSUE TITLE
Error: Taxi Node Mismatch

### ISSUE THREAD

**Issue by Phanx** [Phanx/Hydra#4]
Originally reported on WoWInterface:

**[sconley](http://www.wowinterface.com/forums/member.php?action=getinfo&userid=43178)**:
> Error: Taxi Node Mismatch
> In WOD, I'm getting this all the time. My toons are not never taking a flightpath automatically.

**Reply # 1 by me:**
> This message indicates that your secondary character(s) were unable to find a flight path whose name matched the one your primary character took.
>
> Replace your Modules/Taxi.lua file with the one found here:
> https://raw.githubusercontent.com/Phanx/Hydra/master/Modules/Taxi.lua
>
> Then reload your UI (if you were already logged into WoW) and enable debugging for the Taxi module in the Hydra options panel, go take a taxi, and report back with the debugging messages printed to your chat frame on the character that selected the taxi, and one of your other characters.

**Reply # 2 by sconley:**
> I updated taxi.lua.  
> If all of my toons have the flight master window open, all of them will take the same flight. If one opens and selects a flight, followed within a few seconds by another toon, the 2nd toon does not automatically accept the flight.

**Reply # 3 by me:**
> Can you provide the debugging output in that scenario?

**Reply # 4 by sconley:**
> I have a 5 minion team. All 5 toons are at the same flight master. I open flighmaster windows on one toon and select a flight.
>
> I go to 2nd toon and open flight master window. Nothing happens. I manually selecte the flight.
>
> Here is part of the output of debug (I'm retyping, don't know if there is an easier way to get it):
>
>> Broadcasting taxi node 23 Iron Docks, Gorgrond
>> SendAddonMessage Taxi Iron Docks, Gorgond PARTY
>> Comm received from Toon-Server -> UNKNOWN
> 
> On the 2nd toon, I also got:
>
>> ERROR: Toon-Server : Taxi node mismatch.

**Reply # 5 by me:**
> That's the only message you got on the second toon? There was no message indicating that the comm from the first toon (with the name of the flight destination) was received?

**Reply # 6 by sconley:**
> You should add a copy chat feature to PhanxChat. (smile).
>
> On toon one, when I selected a flight, I got the following:
>
>> Broadcasting taxi node 23 Wildwood Wash, Gorgrond
>> SendAddonMessage Taxi Wildwood Wash, Gorgrond PARTY
>> Com received from <another toon> -> UNKNOWN
>
> (I got the above line for each of the 4 other toons in my party)
>
> On toon 2, I got the following when toon 1 took a flight:
>
>> Comm received from <toon1> -> Wildwood Wash, Gorgrond
>> <toon1> set the group taxi to Wildwood Wash, Gorgrond
>> TAXIMAP_OPENED Taxi UNKNOWN PARTY
>> Com received from <toon3 thru 5> -> UNKNOWN
>
> Hope that helps. If not, I can try to post a screen shot.

**Comment by fireymerlin** [comment]
Here is what I did to fix the problem in my copy of taxi.lua:
Add the following right after "function module:TAXIMAP_OPENED()" (line 59):
	if not TaxiRouteMap:IsShown() or not (NumTaxiNodes() > 0) then return end

**Comment by Phanx** [comment]
I'm not sure why `NumTaxiNodes()` would ever return 0 when you open the flight map -- even if you don't know any other flight paths, you at least know the one you clicked on to open the map -- but if that is actually happening for you (and presumably the original poster) I guess that could explain why I have not able to reproduce the problem.

However, I'm not sure how your proposal actually solves the problem either. Are you seeing `TAXIMAP_OPENED` fire *twice* when you click on the flight master? Once before the frame is actually shown and/or before node data is available, and then again after the frame becomes shown and data is available?

**Comment by fireymerlin** [comment]
I took my changes out and instead put a print(TaxiRouteMap:IsShown(), NumTaxiNodes())
Testing with 2 man team.
When I opened a FlightMaster on one toon, I got the following display just on that toon:
true  44
When I selected a destination, I got the following on the toon that selected it:
Hydra:  ERROR:  Toon2-Realm:  Taxi nodemismatch.
On the other toon, I got the following:
Hydra:  Toon1-Realm set the group taxi to Stormshield.
true   0

The other toon did not have the flight master open.
If the other toon has the flight master open before I select a location, I do not get the error.
Sounds like the error is being caused when one of the other toons does not have the flight master open.
My fix was a force fix.  I'm sure there is a better way.

**Comment by Phanx** [comment]
It sounds like the problem may actually be here:

		if TaxiRouteMap:IsShown() then
			self:TAXIMAP_OPENED()
		end

This was added in response to someone's request to have taxi sharing work if all the other toons already had the flight master window open. Try changing `IsShown` to `IsVisible` and let me know if that solves the problem; you shouldn't see that last `true 0` on the secondary toon(s) or the error message returned to the primary toon.

**Comment by fireymerlin** [comment]
Your change fixed the problem.
I tested it with a 5 man team.
With 1 toon with flight master open when selecting destination.
With 3 toons with flight master open when selecting destination.
Thanks.
